checkpoints_path: ./experiments/
evolutionary:
  generations: 5
  lambda: 3
  max_epochs: 10000
  mutation:
    add_connection: 0.
    remove_connection: 0.0
    add_layer: 0.8
    reuse_layer: 0.8
    remove_layer: 0.8
    dsge_layer: 0.8
    macro_layer: 0.8
    train_longer: 0.2
network:
  architecture:
    reuse_layer: 0.8
    network_structure:
      -
        - features
        - 1
        - 2
      - 
        - classification
        - 1
        - 2
    macro_structure:
      - learning
    output: softmax
    network_structure_init: {features: [1], classification:[1]}
    levels_back: {features: 1, classification: 1}
  learning:
    learning_type: supervised
    augmentation: null
    default_train_time: 5
    fitness_metric: accuracy