name: evodenss
channels:
  - conda-forge
  - pytorch

dependencies:
  - python=3.10
  - pytorch=2.0.0
  - torchvision=0.15.2
  - torchmetrics=1.1.1
  - scikit-learn=1.3.0
  - jsonschema=4.4.0
  - PyYAML=6.0.1
  - versioneer=0.29
  - llvm-openmp<16
  - coverage=7.3.2
  - pytest=7.4.2
  - parameterized=0.9.0
  