name: fast-denser-torch
channels:
  - pytorch
  - conda-forge
  - default

dependencies:
  - python=3.9
  - cudatoolkit=11.3.*
  - jsonschema=4.4.0
  - numpy=1.21.5
  - Pillow=9.0.1
  - pytorch=1.12.0
  - torchvision=0.13.0
  - PyYAML=5.4.1
  - torchmetrics=0.9.2
  - scikit-learn=1.1.2
  - pip
  - pip:
    - argparse==1.4.0