type: object
properties:
  checkpoints_path:
    type: string
  evolutionary:
    type: object
    properties:
      generations:
        type: integer
        minimum: 1
      lambda:
        type: integer
        minimum: 1
      max_epochs:
        type: integer
        minimum: 1
      mutation:
        type: object
        properties:
          add_connection:
            $ref: "#/$defs/mutation_prob"
          remove_connection:
            $ref: "#/$defs/mutation_prob"
          add_layer:
            $ref: "#/$defs/mutation_prob"
          reuse_layer:
            $ref: "#/$defs/mutation_prob"
          remove_layer:
            $ref: "#/$defs/mutation_prob"
          dsge_layer:
            $ref: "#/$defs/mutation_prob"
          macro_layer:
            $ref: "#/$defs/mutation_prob"
          train_longer:
            $ref: "#/$defs/mutation_prob"
        additionalProperties: False
        required: 
          - add_connection
          - remove_connection
          - add_layer
          - reuse_layer
          - remove_layer
          - dsge_layer
          - macro_layer
          - train_longer
    additionalProperties: False
    required: 
      - generations
      - lambda
      - max_epochs
      - mutation
  network:
    type: object
    properties:
      architecture:
        type: object
      learning:
        type: object
        properties:
          learning_type:
            enum: [supervised, self-supervised]
          default_train_time:
            type: integer
          fitness_metric:
            enum: [accuracy, loss]
          augmentation:
            type: object
            properties:
              train:
                allOf:
                  - 
                    if:
                      properties:
                        learning_type:
                          const: 'supervised'
                    then:
                      oneOf:
                        - type: object
                        - type: 'null'
                  - 
                    if:
                      properties:
                        learning_type:
                          const: 'self-supervised'
                    then:
                      properties:
                        input_a:
                          type: object
                        input_b:
                          type: object
              test:
                oneOf:
                  - type: object
                  - type: 'null'
            additionalProperties: False
        additionalProperties: False
        required: 
          - learning_type
          - default_train_time
          - fitness_metric
          - augmentation
    additionalProperties: False
    required: 
      - architecture
      - learning
additionalProperties: False
required: 
  - checkpoints_path
  - evolutionary
  - network
$defs:
  mutation_prob:
    type: number
    minimum: 0
    maximum: 1
  augmentation_params:
    type: array
    items:
      type: object
      properties:
        name:
          enum: [random_resized_crop, random_horizontal_flip, color_jitter, random_grayscale, gaussian_blur, random_solarize, normalize]
        params:
          type: object