checkpoints_path: ../../results/experiments_bt_cifar_identity_lower_prob_mutations/
evolutionary:
  generations: 100
  lambda: 4
  max_epochs: 10000
  mutation:
    add_connection: 0.0
    remove_connection: 0.0
    add_layer: 0.25
    reuse_layer: 0.15
    remove_layer: 0.25
    dsge_layer: 0.15
    macro_layer: 0.3
    train_longer: 0.2
network:
  architecture:
    reuse_layer: 0.15
    network_structure:
      - 
        - features
        - 1
        - 30
    macro_structure:
      - learning
    output: identity
    network_structure_init: {features: [2,3,4]}
    levels_back: {features: 1}
  learning:
    learning_type: self-supervised
    augmentation:
      train:
        input_a:
          random_resized_crop:
            size: 32
          random_horizontal_flip:
            probability: 0.5
          color_jitter:
            brightness: 0.4
            contrast: 0.4
            saturation: 0.4
            hue: 0.1
            probability: 0.8
          random_grayscale:
            probability: 0.2
          normalize:
            mean: [0.4914, 0.4822, 0.4465]
            std: [0.2023, 0.1994, 0.2010]
        input_b:
          random_resized_crop:
            size: 32
          random_horizontal_flip:
            probability: 0.5
          color_jitter:
            brightness: 0.4
            contrast: 0.4
            saturation: 0.4
            hue: 0.1
            probability: 0.8
          random_grayscale:
            probability: 0.2
          normalize:
            mean: [0.4914, 0.4822, 0.4465]
            std: [0.2023, 0.1994, 0.2010]
      last_layer_train:
        random_resized_crop:
          size: 32
        random_horizontal_flip:
          probability: 0.5
        color_jitter:
          brightness: 0.4
          contrast: 0.4
          saturation: 0.4
          hue: 0.1
          probability: 0.8
        random_grayscale:
          probability: 0.2
        normalize:
          mean: [0.4914, 0.4822, 0.4465]
          std: [0.2023, 0.1994, 0.2010]
      test:
        normalize:
          mean: [0.4914, 0.4822, 0.4465]
          std: [0.2023, 0.1994, 0.2010]
    default_train_time: 300
    fitness_metric: accuracy