checkpoints_path: ../../results/experiments_bt_cifar_identity_resnet3/
evolutionary:
  generations: 100
  lambda: 9
  max_epochs: 100000
  mutation:
    add_connection: 0.0
    remove_connection: 0.0
    add_layer: 0.1
    reuse_layer: 0.1
    remove_layer: 0.1
    dsge_layer: 0.1
    macro_layer: 0.4
    train_longer: 0.04
network:
  architecture:
    reuse_layer: 0.1
    network_structure:
      - 
        - features_1
        - 1
        - 6
      -  
        - features_2
        - 1
        - 6
      -
        - features_3
        - 1
        - 6
      -
        - features_4
        - 1
        - 6
      -
        - features_5
        - 1
        - 6
    macro_structure:
      - learning
    output: identity
    network_structure_init: {features_1: [2,3,4], features_2: [2,3,4], features_3: [2,3,4], features_4: [2,3,4], features_5: [2,3,4]}
    levels_back: {features_1: 1, features_2: 1, features_3: 1, features_4: 1, features_5: 1}
  learning:
    learning_type: self-supervised
    augmentation:
      train:
        input_a:
          random_resized_crop:
            size: 32
          random_horizontal_flip:
            probability: 0.5
          color_jitter:
            brightness: 0.4
            contrast: 0.4
            saturation: 0.4
            hue: 0.1
            probability: 0.8
          random_grayscale:
            probability: 0.2
          normalize:
            mean: [0.4914, 0.4822, 0.4465]
            std: [0.2023, 0.1994, 0.2010]
        input_b:
          random_resized_crop:
            size: 32
          random_horizontal_flip:
            probability: 0.5
          color_jitter:
            brightness: 0.4
            contrast: 0.4
            saturation: 0.4
            hue: 0.1
            probability: 0.8
          random_grayscale:
            probability: 0.2
          normalize:
            mean: [0.4914, 0.4822, 0.4465]
            std: [0.2023, 0.1994, 0.2010]
      last_layer_train:
        random_resized_crop:
          size: 32
        random_horizontal_flip:
          probability: 0.5
        color_jitter:
          brightness: 0.4
          contrast: 0.4
          saturation: 0.4
          hue: 0.1
          probability: 0.8
        random_grayscale:
          probability: 0.2
        normalize:
          mean: [0.4914, 0.4822, 0.4465]
          std: [0.2023, 0.1994, 0.2010]
      test:
        normalize:
          mean: [0.4914, 0.4822, 0.4465]
          std: [0.2023, 0.1994, 0.2010]
    default_train_time: 60
    fitness_metric: accuracy